# https://github.com/chenrui333/homebrew-tap/blob/main/.github/workflows/autobump.yml
name: Bump formulae on schedule or request

on:
    push:
        branches:
            - main
        paths:
            - .github/workflows/autobump.yml
    workflow_dispatch:
        inputs:
            formulae:
                description: Custom list of formulae to livecheck and bump if outdated
                required: false
    schedule:
        - cron: "15 */2 * * *"

jobs:
    autobump:
        runs-on: ubuntu-24.04
        steps:
            - name: Set up Homebrew
              id: set-up-homebrew
              uses: Homebrew/actions/setup-homebrew@main
              with:
                  core: false
                  cask: false
                  test-bot: false

            - name: Configure Git user
              uses: Homebrew/actions/git-user-config@main
              with:
                  username: BrewTestBot

            - name: Get list of autobump formulae
              id: autobump
              run: |
                  autobump_list=$(brew tap-info amrkmn/tap --json | \
                    jq -c -r '.[0]["formula_names"] | join(" ")')
                  echo "autobump_list=$autobump_list" >> "$GITHUB_OUTPUT"

            - name: Bump formulae
              uses: Homebrew/actions/bump-packages@main
              continue-on-error: true
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  formulae: ${{ github.event.inputs.formulae || steps.autobump.outputs.autobump_list }}
                  fork: false
