name: brew test-bot

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test-bot:
        runs-on: ubuntu-22.04
        permissions:
            actions: read
            checks: read
            contents: read
            packages: read
            pull-requests: write
        steps:
            - name: Set up Homebrew
              id: set-up-homebrew
              uses: Homebrew/actions/setup-homebrew@main
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - name: Cache Homebrew Bundler RubyGems
              uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
              with:
                  path: ${{ steps.set-up-homebrew.outputs.gems-path }}
                  key: linux-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
                  restore-keys: linux-rubygems-

            - run: brew test-bot --only-cleanup-before

            - run: brew test-bot --only-setup

            - run: brew test-bot --only-tap-syntax
            - name: Base64-encode FORGEJO_PACKAGE_TOKEN for HOMEBREW_DOCKER_REGISTRY_TOKEN
              id: base64-encode
              if: github.event_name == 'pull_request'
              env:
                  TOKEN: ${{ secrets.FORGEJO_PACKAGE_TOKEN }}
              run: |
                  base64_token=$(echo -n "${TOKEN}" | base64 | tr -d "\n")
                  echo "::add-mask::${base64_token}"
                  echo "token=${base64_token}" >> "${GITHUB_OUTPUT}"
            - run: brew test-bot --only-formulae --root-url=https://noz.one/v2/pkgs/tap
              if: github.event_name == 'pull_request'
              env:
                  HOMEBREW_DOCKER_REGISTRY_TOKEN: ${{ steps.base64-encode.outputs.token }}

            - name: Upload bottles as artifact
              if: always() && github.event_name == 'pull_request'
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                  name: bottles_linux
                  path: "*.bottle.*"

            - name: Add pr-pull label
              if: github.event_name == 'pull_request' && success()
              uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8 # v1.1.0
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  labels: pr-pull
