name: brew test-bot

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# https://github.com/chenrui333/homebrew-tap/blob/51e2b1829bd82a7ff165dc7aa84239aff89192ca/.github/workflows/tests.yml#L17
env:
    HOMEBREW_DEVELOPER: 1
    HOMEBREW_GITHUB_ACTIONS: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_FROM_API: 1
    HOMEBREW_TEST_BOT_ANALYTICS: 1
    HOMEBREW_ENFORCE_SBOM: 1
    HOMEBREW_NO_BUILD_ERROR_ISSUES: 1
    HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
    HOMEBREW_RELOCATABLE_INSTALL_NAMES: 1
    HOMEBREW_NO_REQUIRE_TAP_TRUST: 1
    GH_REPO: ${{ github.repository }}
    GH_NO_UPDATE_NOTIFIER: 1
    GH_PROMPT_DISABLED: 1
    PR: ${{ github.event.number }}

jobs:
    test-bot:
        strategy:
            matrix:
                os: [macos-26, ubuntu-24.04, ubuntu-24.04-arm]
        runs-on: ${{ matrix.os }}

        permissions:
            actions: read
            checks: read
            contents: read
            packages: read
            pull-requests: write

        steps:
            - name: Set up Homebrew
              id: set-up-homebrew
              uses: Homebrew/actions/setup-homebrew@main
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - name: Cache Homebrew Bundler RubyGems
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: ${{ steps.set-up-homebrew.outputs.gems-path }}
                  key: ${{ runner.os }}-${{ runner.arch }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
                  restore-keys: ${{ runner.os }}-${{ runner.arch }}-rubygems-

            - run: brew test-bot --only-cleanup-before

            - run: brew test-bot --only-setup

            - run: brew test-bot --only-tap-syntax

            - name: Base64-encode GH_TOKEN for HOMEBREW_DOCKER_REGISTRY_TOKEN
              id: base64-encode
              if: github.event_name == 'pull_request'
              env:
                  TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  base64_token=$(echo -n "${TOKEN}" | base64 | tr -d "\n")
                  echo "::add-mask::${base64_token}"
                  echo "token=${base64_token}" >> "${GITHUB_OUTPUT}"

            - run: brew test-bot --only-formulae --root-url=https://ghcr.io/v2/amrkmn/tap
              if: github.event_name == 'pull_request'
              env:
                  HOMEBREW_DOCKER_REGISTRY_TOKEN: ${{ steps.base64-encode.outputs.token }}

            - name: Upload bottles as artifact
              if: always() && github.event_name == 'pull_request'
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: bottles_${{ matrix.os }}_${{ github.run_id }}
                  path: "*.bottle.*"

    add-label:
        name: Add 'pr-pull' label to PR
        needs: [test-bot]
        if: github.event_name == 'pull_request' && success()
        runs-on: ubuntu-24.04
        steps:
            - name: Add pr-pull label
              uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8 # v1.1.0
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  labels: pr-pull
